f = open("/home/molto/Desktop/odoo/Untitled Document 1", "a+")
f.write()
print("what i have learned today?" "\n")
a = input("-your answer: ")
print("What new skills i need?" "\n")
b = input("-your answer: ")
print("What is my expectations?" "\n")
c = input("-your answer: ")
print(" How was the day for me?" "\n")
